Repository home-assistant/analytics.home-assistant.io, pull requests merged in 2022-10, with the labels that each got.

#638 Rewrite to use 11ty
  .gitignore
  package.json
  script/build
  script/develop
  site/.eleventy.js
  site/index.html
  site/src/_layouts/base.html
  site/src/_layouts/table.html
  site/src/_static/styles.css
  site/src/add-ons.html
  site/src/analytics-active-installations.ts
  site/src/analytics-addons.ts
  site/src/analytics-element.ts
  site/src/analytics-header.ts
  site/src/analytics-installation-types.ts
  site/src/analytics-integrations.ts
  site/src/analytics-map.ts
  site/src/analytics-median.ts
  site/src/analytics-os-boards.ts
  site/src/analytics-os-versions.ts
  site/src/analytics-releases.ts
  site/src/analytics-version-history.ts
  site/src/components/analytics-chart.ts
  site/src/data.ts
  site/src/datasets.liquid
  site/src/index.html
  site/src/integrations.html
  site/src/statistics.html
  site/src/tools/calculate.js
  site/src/tools/colors.js
  site/src/tools/data_table.js
  site/src/tools/friendly_names.js
  site/src/tools/history_filter.js
  site/src/tools/versions.js
  site/tsconfig.json
  worker/tests/mock.ts
  yarn-error.log
  yarn.lock
Labels: cla-signed, WTH

#641 Rename Z-Wave JS UI addon
  site/src/add-ons.html
Labels: cla-signed

#646 Use 1 more month of weekly values
  site/src/tools/history_filter.js
Labels: cla-signed, Hacktoberfest

#647 Merge dev into main
  .github/workflows/test.yaml
  .github/workflows/worker.yaml
  package.json
  site/src/add-ons.html
  site/src/tools/colors.js
  site/src/tools/history_filter.js
  yarn.lock
Labels: cla-signed, Hacktoberfest
